### ISSUE TITLE
session ended, but player indicated that the session still has time in it.

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#57] opened 2017-02-05 09:08 UTC
![end_game_with_time_left_ink_li](https://cloud.githubusercontent.com/assets/18185033/22625009/761f12aa-eb93-11e6-9d80-6766c54aa756.jpg)

**Comment by sebastientromp** [comment] 2017-02-05 09:11
Could you please attach the hearthstone logs? It's strange that the "end game" label is displayed without any clear end game screen

**Comment by ililush** [comment] 2017-02-05 10:09
[Logs.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/752865/Logs.zip)

here is my entire log library

**Comment by sebastientromp** [comment] 2017-02-05 18:37
Could not reproduce, but probably linked to #56. Marking it as fixed, let me know if you can still reproduce

**Closed** 2017-02-06 08:16 UTC
Labels: Can be closed, Fixed - Needs OW validation, Show stopper
