### ISSUE TITLE
cannot see recent match in GS

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#35] opened 2017-01-15 08:11 UTC
finished a game (and lost in it) but i do not see it in the GS.
![cannot_see_recent_match](https://cloud.githubusercontent.com/assets/18185033/21961147/a80c80c0-db0a-11e6-8bc1-8a523662086c.png)

**Comment by ililush** [comment] 2017-01-15 08:11
[Log.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/706466/Log.zip)

**Comment by sebastientromp** [comment] 2017-01-15 08:41
I'm not really familiar with OW logs - which files should I be looking into?
Could you also include the Hearthstone Logs in case the issue comes from parsing the game itself?

**Comment by ililush** [comment] 2017-01-15 08:50
Where can i find the HS logs?

**Comment by sebastientromp** [comment] 2017-01-15 09:39
In Hearthstone installation folder /Logs, replay file is called Power.log

Closing this issue, as it's a duplicate of #28

**Closed by sebastientromp** 2017-01-15 09:39 UTC
