### ISSUE TITLE
user is placed at the top of the screen and not at the bottom

### ISSUE THREAD

**Issue by ililush** [Zero-to-Heroes/overwolf-replay-app#44] opened 2017-01-16 12:15 UTC
for all three matches in this session.

log file for this session is attached.
![screenshot_16](https://cloud.githubusercontent.com/assets/18185033/21982663/2b8e7f98-dbf6-11e6-82c2-576eb406b3a9.png)

**Comment by sebastientromp** [comment] 2017-01-16 12:45
Could you please detail the expected behavior? I'm not sure I got it :)

**Comment by sebastientromp** [comment] 2017-01-16 20:30
Ah, I think I got it :)
However I don't see any log files, would you mind re-attaching them?

**Comment by ililush** [comment] 2017-01-17 04:39
sure!


[hearthstone_2017_01_16_13_29_02.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/710021/hearthstone_2017_01_16_13_29_02.zip)

**Comment by sebastientromp** [comment] 2017-01-17 06:16
Unfortunately these logs don't have the game info - I'm looking for the Power.log or Power_old.log that has the game's info (you can search for your opponent's names to know if they have been overwritten already)

**Comment by ililush** [comment] 2017-01-17 07:21
is it possible that such a log was not created?

**Comment by sebastientromp** [comment] 2017-01-17 08:12
It's always created (that's what I parse to reconstruct the games), however HS overwrites it regularly. I don't know the exact pattern, but if you relaunch HS it usually removes the Power.log if it dates back from the day before or earlier

**Comment by ililush** [comment] 2017-01-18 07:07
will test again today to see if this re-occures.

**Comment by ililush** [comment] 2017-01-22 09:20
was able to recreate this. 
log attached
![i m_placed_at_the_top_view_as_if_i ve_switched_places_with_the_opponent](https://cloud.githubusercontent.com/assets/18185033/22181420/bb2b38d8-e094-11e6-87a3-04cbd038f618.png)

[Power_old.zip](https://github.com/Zero-to-Heroes/overwolf-replay-app/files/721831/Power_old.zip)

**Comment by sebastientromp** [comment] 2017-01-22 10:08
Looks like this happens only for the most recent game. The logs indicate that the games are parsed properly (the main player is properly identified in both cases), but for some reason the display is inversed for the latest one.
Still looking into it

**Comment by sebastientromp** [comment] 2017-01-22 10:49
I found a place in the replay viewer where state from the previous parsed game was leaking, should be fixed now

**Closed** 2017-02-05 08:57 UTC
Labels: Can be closed, Fixed - Needs OW validation
