### ISSUE TITLE
Pause button is not working - Replay continues to play even after the Pause button is pressed

### ISSUE THREAD

**Issue by yanco77** [Zero-to-Heroes/overwolf-replay-app#49] opened 2017-01-31 08:14 UTC
This issue was first encountered in app version 0.16.

Repro:
1) Game Summary is opened.
2) Click on the Play button (Replay starts, Play button changes its icon to Pause icon).
3) Click on the Pause button.

Result:
1) The replay does not pause (it continues to play).
2) Consecutive presses on the Play/Pause button will toggle the Play/Pause icons but will not affect the replay (player is stuck in play mode)

Expected result:
Player behaves according to the Play/Pause button state

**Comment by sebastientromp** [comment] 2017-02-05 18:37
Any update on the video / gif for me to see the exact steps you're taking? Still can't reproduce it on my side, play/pause buttons work properly

**Comment by ililush** [comment] 2017-02-06 06:49
i cannot reproduce, so this can be closed.

**Comment by sebastientromp** [comment] 2017-02-06 09:49
Re-opening just for a check. Apprently yanco did a QA session where several of them could reproduce the issue. Could you please just double-check with them and let me know (I'll close it then)?

**Comment by ililush** [comment] 2017-02-06 10:18
We are having an additional QA session today specifically to check if this still reproduces on other computers, and to check the carousel arrows :)

**Closed** 2017-02-06 18:34 UTC
Labels: Can be closed, Show stopper
